### ISSUE TITLE
No access to root/Magisk error on A13 DP1

### ISSUE THREAD

**Issue by nezorflame** [Fox2Code/FoxMagiskModuleManager#81] opened 2022-02-16 16:13 UTC
Pixel 6, A13 DP1.

While launching the app, it shows a red box with an error which is roughly translated to "Unable to get root access or Magisk...".
Magisk haven't shown any root requests from the app.

Haven't noticed anything specific in the logcat, but can still provide it if required.

**Comment by Fox2Code** [comment] 2022-02-17 12:38
Common Magisk issue, just grant manually root access in the Magisk app directly, if it doesn't work it's an issue with the libsu library, because my app is relying on this library to ask for root.

I think for now the best thing to do is to wait a bit, a fix in libsu will probably come very soon.

**Comment by Fox2Code** [comment] 2022-02-17 12:40
https://github.com/topjohnwu/libsu <- I followed it to see if there is any update on there.

Also please use canary if you can when playing on experimental Android build.

**Comment by nezorflame** [comment] 2022-02-17 14:16
Gotcha, thanks for the info!

**Comment by Fox2Code** [comment] 2022-02-17 15:02
For now I will ignore but not close the issue while waiting for more info.
If you have more info please post them here or on telegram -> https://t.me/Fox2Code_Chat

**Comment by Fox2Code** [comment] 2022-03-03 13:57
Please test the issue again with `0.4.0-rc1`

**Comment by swilger** [comment] 2022-03-04 11:47
I have this bug with 0.4.0-rc1 release. I had to reinstall 0.32, there it is working just fine. Magisk canary 24.2

**Comment by Fox2Code** [comment] 2022-03-04 12:11
This error is beyond my current understanding.

**Comment by Fox2Code** [comment] 2022-03-04 12:16
@swilger and @nezorflame please build debug from source and give me a logcat of the app.
I currently don't have enough information to fix this bug, and I did my best to try to fix it blindly.
This error is not occurring on any of my devices, so I can't reproduce it and get more info about it.

**Comment by nezorflame** [comment] 2022-03-04 13:35
This works on latest Magisk Canary, so your initial suggestion helped.

**Comment by swilger** [comment] 2022-03-04 23:09
I will do provide logcat. Give me some time, im actually busy, but as soon as i have some rest, i will take care. Thx for ur help

**Comment by Fox2Code** [comment] 2022-03-10 21:01
Test if [`0.4.0-rc2`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.4.0-rc2) fixed the issue please.

If it doesn't work use debug build and give a `logcat` of the error.

**Comment by Fox2Code** [comment] 2022-03-25 18:47
@swilger your issue does not seems to be linked to the original post, please open a new issue if you are affected by a similar bug.

**Closed by Fox2Code** 2022-03-25 18:47 UTC
Labels: bug, external
