### ISSUE TITLE
[Help] Another Root Access Bug

### ISSUE THREAD

**Issue by elyckir** [Fox2Code/FoxMagiskModuleManager#318] opened 2023-05-02 01:29 UTC
Getting a "Root has been denied" error.
Upon opening the app Magisk gives the popup "was granted superuser access".
 
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11368993/logs.txt)
![Screenshot_20230501-210546_Foxs_Magisk_Module_Manager](https://user-images.githubusercontent.com/67302729/235559354-b217d5d0-21c6-41db-b9a1-8af4098bad91.png)

<sub> LG-H830
Lineage OS 19-20230426
Magisk 26.1 </sub>

**Comment by VSeryi** [comment] 2023-05-02 09:31
Did you triy that build? : https://github.com/Fox2Code/FoxMagiskModuleManager/issues/303#issuecomment-1528926357

**Comment by androidacy-user** [comment] 2023-05-02 19:37
Duplicate of #303

**Closed as completed by androidacy-user** 2023-05-02 19:37 UTC
Labels: bug, waiting for triage

**Comment by elyckir** [comment] 2023-05-04 01:47
The [debug build](https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4841982502) works in fetching modules and installing them 1 by 1 but it weirdly affects Magisk ...
![Screenshot_20230503-214213_Magisk](https://user-images.githubusercontent.com/67302729/236091191-548c6630-a549-4450-9ebc-2c24329e13e4.png)
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11392355/logs.txt)
It often leads to an OS restart or a black screen. 
Uninstalling the debug build returns Magisk to normal
