### ISSUE TITLE
The module zip fails to be downloaded from alt repo

### ISSUE THREAD

**Issue by gjf** [Fox2Code/FoxMagiskModuleManager#13] opened 2021-12-27 16:31 UTC
The issue is described here: https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak/issues/2

Any comments on this? Is it MM issue or repo issue?
Please be so kind to get involved.

**Comment by Fox2Code** [comment] 2021-12-28 15:47
I investigated the issue, the issue is with the remote module json generator.
I will work on it but please be patient, and thank for reporting the issue.

**Comment by Fox2Code** [comment] 2021-12-28 16:29
Fix is on it's way, you should wait a bit tho before the bug is fixed.

**Comment by gjf** [comment] 2021-12-28 16:41
> Fix is on it's way, you should wait a bit tho before the bug is fixed.

So it was MM bug, not repo's?

**Comment by Fox2Code** [comment] 2021-12-28 21:29
Should be fixed, it was a Magisk-Modules-Alt-Repo issue, I worked directly with @tytydraco to fix the issue.

Please clear app cache if the issue is still there.

**Closed by Fox2Code** 2021-12-28 21:29 UTC
Labels: bug, external

**Comment by gjf** [comment] 2021-12-28 21:33
> Should be fixed, it was a Magisk-Modules-Alt-Repo issue, I worked directly with @tytydraco to fix the issue.
> 
> Please clear app cache if the issue is still there.

Not the cache only but all app's data.
And yup - case is closed now.
Thank you.

**Comment by gjf** [comment] 2021-12-29 10:28
> Weird, all online repo data should be stored on the cache folder...
> 
> Probably because just deleting disk cache doesn't delete RAM cache, I will do a fix for that later.

I wrote it already: I really think some button to perform "cleaning" needs to be presented in interface. Because I have to perform deleting from system settings.
Also weird why the app does not perform cleaning cache when updating info from repos automatically?

**Comment by Fox2Code** [comment] 2021-12-29 15:22
App compare cache to downloaded index to avoid downloading already up to date `module.prop`, and when it does the scan it, it also delete removed modules, making cache always as small as necessary.
This avoid reduce the amount of request making the online module list update much quicker.
You can take a look at it here:
https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/java/com/fox2code/mmm/repo/RepoData.java
