### ISSUE TITLE
phone stuck on Android10

### ISSUE THREAD

**Issue by YenKoc** [Fox2Code/FoxMagiskModuleManager#75] opened 2022-02-10 02:19 UTC
when I use this app, click some button to use function,but my phone stuck and screen color turn to black, It is strange.

**Comment by Fox2Code** [comment] 2022-02-10 12:48
This seems to be a device specific issue, it will be hard to debug this as I can't reproduce it.
Please can you tell me which button is doing a black screen?

**Comment by Fox2Code** [comment] 2022-02-10 12:50
Please also tell me you ROM and device manufacturer.

**Comment by Fox2Code** [comment] 2022-02-10 12:54
I have an Android 10 device and I don't have this issue, please give as much information as possible even if it seems unrelated.

I take bugs very seriously, but this bug might be sadly an issue with your system, but I will still try do a workaround to not trigger it.

**Comment by YenKoc** [comment] 2022-02-10 14:22
> This seems to be a device specific issue, it will be hard to debug this as I can't reproduce it. Please can you tell me which button is doing a black screen?



> I have an Android 10 device and I don't have this issue, please give as much information as possible even if it seems unrelated.
> 
> I take bugs very seriously, but this bug might be sadly an issue with your system, but I will still try do a workaround to not trigger it.

thank you，my phone is pixel4(android10). The front page is normal. I try to install the module, when I click the button, the screen is out of my control, I had to close the app. if you are convenient， i can send you a video about all process happen on my phone. If it is rare, I think you don't spend much time to fix it. I don't have a plan to use it. thank you again!

**Comment by Fox2Code** [comment] 2022-02-11 14:39
Please note that you are the only person I know that have this issue with the manager.
I can't fix this bug until you gave me more information.

**Comment by YenKoc** [comment] 2022-02-11 14:43
> Please note that you are the only person I know that have this issue with the manager. I can't fix this bug until you gave me more information.

ok，today I have a import missions so that i forget to reply you, can you give me a email? I can send you a video.

**Comment by Fox2Code** [comment] 2022-02-11 17:31
K take your time.

**Comment by YenKoc** [comment] 2022-02-12 07:46
> K take your time.

I  send you a video in the morning. The github don't take over it because it is too big for it.  please give your personal email so that i quickly send what you want.

**Comment by Fox2Code** [comment] 2022-02-12 13:01
Email is not private btw -> fox2code@gmail.com

**Comment by YenKoc** [comment] 2022-02-14 03:37
> 
ok , i will

**Comment by Fox2Code** [comment] 2022-02-14 10:58
Telegram chat found that it was a ROM File-manager issue, still under investigation.

**Comment by Fox2Code** [comment] 2022-03-03 13:57
Please test the issue again with `0.4.0-rc1`

**Comment by YenKoc** [comment] 2022-03-04 02:47
> Please test the issue again with `0.4.0-rc1`

nice! bro.  the problem already is fixed.

**Comment by Fox2Code** [comment] 2022-03-04 12:09
K closing because the problem is fixed.

**Closed by Fox2Code** 2022-03-04 12:09 UTC
Labels: bug, external
