### ISSUE TITLE
[CRITICAL BUG] Crash after press download icon

### ISSUE THREAD

**Issue by UnrealKaraulov** [Fox2Code/FoxMagiskModuleManager#108] opened 2022-03-29 17:49 UTC
**Describe the bug**
Crash after press download icon at any module.

**To Reproduce**
1. Go to Fox Magisk Module Manager 0.4.0
2. Scroll down to any module.
3. Click on 'download' picture.

**Expected behavior**
Download module button works.

**Screenshots**
Just crash while load download page and ads.

**Device info(please complete the following information):**
 - Device: NOKIA 3.1
 - OS: Android 8.1
 - App Version 0.4.0

**Additional context**

**Comment by UnrealKaraulov** [comment] 2022-03-29 18:06
@Fox2Code I tried multiple version (latest 5 versions) and I got crash after load ads at page. (At one moment I see buttons at bottom of page, and got crash)

**Comment by Fox2Code** [comment] 2022-03-30 12:30
I tried to reproduce the bug you described but couldn't, please send more information about the issue.
Downloading the debug build and giving a logcat would be cool, or you could use Scoop to get the crash if it was an application crash.

**Comment by Fox2Code** [comment] 2022-03-30 12:31
Oops, miss-clicked the close button.

**Comment by UnrealKaraulov** [comment] 2022-03-30 13:57
It works with Android 10 (nokia 3.1) but crash with Andoid 8.1 (nokia 3.1), How I can get logcat with debug build?

**Comment by Fox2Code** [comment] 2022-03-31 12:50
You need to use `adb logcat` on computer or https://github.com/TacoTheDank/Scoop on Android
Scoop is not a full logcat but is often enough to get most crashes info.

**Comment by Fox2Code** [comment] 2022-04-03 11:39
Still no logcat or debug logs, issue will be closed if I do not have a response in a reasonable time.

If you are busy and can't provide a logcat/stacktrace because you are busy please tell me when you will be able to provide it.
Also if I close this issue before you had time to respond, please know that you will be welcomed to open a new one.

**Comment by Fox2Code** [comment] 2022-04-08 14:14
No response in a reasonable time, closing issue, please open a new one if you still have the issue.

**Closed by Fox2Code** 2022-04-08 14:14 UTC
Labels: bug, not enough info

**Comment by UnrealKaraulov** [comment] 2022-04-12 07:53
I just don't use this tool because it crashes

**Comment by Fox2Code** [comment] 2022-04-12 13:44
Well you didn't gave me any proof and no one else is reporting me a crash.
Marking issue as invalid as you purposefully reported an issue without giving any info about the crash.
