### ISSUE TITLE
Change module download location

### ISSUE THREAD

**Issue by InnerCato** [Fox2Code/FoxMagiskModuleManager#77] opened 2022-02-12 09:36 UTC
Can you add an option to change the module download location like in Magisk?

**Comment by Fox2Code** [comment] 2022-02-12 10:24
My app open your web browser to download.

As such it doesn't choose download location.

This is mainly done so I don't have to ask extra perms for storage, I really don't like asking for perms in an app unless necessary.

Please change you browser settings to ask every time.

**Comment by Fox2Code** [comment] 2022-02-12 10:27
Also I could make download managed by the app in the future instead of using the external web browser so I will keep this an an enhancement request.

**Comment by InnerCato** [comment] 2022-02-13 05:45
Ok

**Comment by Fox2Code** [comment] 2022-03-03 17:21
Is this a duplicate of #60?

**Closed** 2022-03-04 17:10 UTC
Labels: enhancement
