### ISSUE TITLE
[BUG] No Online Repo Shown on Pixel 6/Android 12

### ISSUE THREAD

**Issue by d8ahazard** [Fox2Code/FoxMagiskModuleManager#103] opened 2022-03-16 13:29 UTC
**Describe the bug**
New install of the "non-debug" version on a Pixel 6 Pro Running android 12. No online repos are shown in the main UI.

**To Reproduce**
Install on a Pixel 6 Pro.

**Comment by Fox2Code** [comment] 2022-03-25 18:45
Closing as unable to reproduce bug, and no proof of bug existing have been shown.

If you wish this issue to be reopened please send screenshot with logcat of the latest debug build having the issue.

If debug builds work for you, there is no downside of using them except for having slightly more RAM and Disk space usage.

**Closed by Fox2Code** 2022-03-25 18:46 UTC
Labels: bug, invalid, not enough info
