### ISSUE TITLE
[BUG] App crash

### ISSUE THREAD

**Issue by old4error** [Fox2Code/FoxMagiskModuleManager#176] opened 2022-07-15 18:17 UTC
**Describe the bug**
App chashes when trying to get a module description by pressing "Description" button

**To Reproduce**
1. Open app
2. Click on "Description" button on any module (local or repo)
4. Expect crash

**Expected behavior**
The app should give me a description of module i guess

**Screenshots**

**Device info(please complete the following information):**
 - Device: POCO X3 Pro
 - OS: ArrowOs 12.1 2022.06.29
 - App Version: 0.5.5

**Additional context**
Log (i guess it is)
Process: com.fox2code.mmm, PID: 8528
07-15 21:07:33.375 E/AndroidRuntime(8528): java.lang.IllegalStateException: Non manager theme!
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at com.fox2code.mmm.MainApplication.h(SourceFile:2)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at x2.y(Unknown Source:4)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at x2.d(Unknown Source:0)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at iu0.f(SourceFile:2)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at com.fox2code.mmm.MainApplication.c(SourceFile:46)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at u70.run(SourceFile:4)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at android.os.Handler.handleCallback(Handler.java:938)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at android.os.Looper.loopOnce(Looper.java:201)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at android.os.Looper.loop(Looper.java:288)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at java.lang.reflect.Method.invoke(Native Method)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
07-15 21:07:33.375 E/AndroidRuntime(8528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Fox2Code** [comment] 2022-07-15 18:18
Duplicate of #175 fixed in `0.5.6`

**Closed by Fox2Code** 2022-07-15 18:18 UTC
Labels: bug, duplicate

**Comment by old4error** [comment] 2022-07-15 18:19
i read that guy's logcat; or i'm blind or there are different errors

**Comment by Fox2Code** [comment] 2022-07-15 18:22
`java.lang.IllegalStateException: Non manager theme!`, you just only provided the error, the guy provided his entire logcat, both ways of doing are fine.

He was just faster than you. :3
