### ISSUE TITLE
incorrect recognition of aml module' part

### ISSUE THREAD

**Issue by admzzz** [Fox2Code/FoxMagiskModuleManager#14] opened 2021-12-28 04:44 UTC
![Screenshot_20211228-073303670](https://user-images.githubusercontent.com/4542575/147528875-c35b4886-5c4a-4d82-bd05-fd69b1012f6c.jpg)

it happens because aml keeps files outside /data/adb/modules, in /data/adb/aml

**Comment by Fox2Code** [comment] 2021-12-28 15:23
This is not an issue but intended behavior, the manager doesn't care about where the files are but only by the `module.prop`.
Since the `module.prop` is missing information, what you are seeing on screen is accurate behavior.

Please ask the owner of the module to fix their generated `module.prop` to include the author, a version and a description.

If you think the behavior of the manager should be changed please give more information how to reproduce the issue.

And also describe what behavior should the manager have for the described issue.

**Comment by Fox2Code** [comment] 2022-01-03 13:59
Closing for failure to provide the required information to process the issue correctly.

If you want to give more details on how you want the issue to be fixed please give the details when you open a new issue.

**Closed by Fox2Code** 2022-01-03 13:59 UTC
Labels: invalid
